services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: wgg-backend
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - /app/node_modules
    working_dir: /app
    command: >
      sh -c "npx prisma migrate deploy &&
             npx prisma generate &&
             npm run dev"

volumes:
  pgdata:
